version: "3.9"

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    # restart: unless-stopped
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks:
      - backend

  # Express.js Server
  backend:
    command: tail -f /dev/null # keeps container running
    depends_on:
      - mongodb
    build: 
      dockerfile: Dockerfile
      context: ./backend
    # restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules/
    networks:
      - backend
      - frontend

  # React.js App Client
  frontend:
    command: tail -f /dev/null # keeps container running
    depends_on: 
      - backend
    build: 
      dockerfile: Dockerfile
      context: ./frontend
      args:
        - REACT_APP_API_BASE_URL=$API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules/
    networks:
      - frontend

volumes:
  db:

networks:
  backend:
  frontend:
