version: '3.3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
     - ./docker-config/mongodb:/data/db
     - ./docker-config/mongodb/initdb:/docker-entrypoint-initdb.d
    ports:
     - '27019:27019'
    networks: 
      - net
  backend:
    build:
      context: ./backend 
    container_name: express
    ports:
     - '3000:3000'
#    expose:
#      - "3000"
    volumes:
      - ./backend:/backend 
      - /backend/node_modules
    restart: "unless-stopped"
    depends_on:
      - mongodb
    networks: 
      - net
networks:
  net:
    driver: bridge