version: "3.9"

services:
  # MongoDB
  mongodb:
    container_name: db
    command: mongod --quiet --logpath /dev/null # disable mongodb verbose logging
    image: mongo:latest
    # restart: unless-stopped
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks:
      - backend

  # Express.js Server
  backend:
    container_name: back
    # command: tail -f /dev/null # DEBUG: uncomment to keep container running
    depends_on:
      - mongodb
    build: 
      dockerfile: Dockerfile.dev # DEV: uses separate Dockerfile for development environment
      context: ./backend
    # restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./backend:/app/backend
      - node_modules_backend:/app/backend/node_modules
      - node_modules_backend:/tmp/node_modules
    networks:
      - backend
      - frontend

  # React.js App Client
  frontend:
    container_name: front
    # command: tail -f /dev/null # DEBUG: uncomment to keep container running
    depends_on: 
      - backend
    build: 
      dockerfile: Dockerfile.dev # DEV: uses separate Dockerfile for development environment
      context: ./frontend
      args:
        - REACT_APP_API_BASE_URL=$API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
      - $REACT_DOCKER_PORT:$REACT_DOCKER_PORT # DEV: open 8080 to local to enable hot reload
    volumes:
      - ./frontend:/app/frontend
      - node_modules_frontend:/app/frontend/node_modules
      - node_modules_frontend:/tmp/node_modules
    networks:
      - frontend

volumes:
  db:
  node_modules_backend:
  node_modules_frontend:

networks:
  backend:
  frontend:
