components:
  schemas:
    User:
      properties:
        id:
          type: string
          description: 고유 Id
          uniqueItems: true
        serviceNumber:
          type: string
          description: 사용자 군번
          uniqueItems: true
        password:
          type: string
          description: 사용자 비밀번호
        name:
          type: string
          description: 사용자 이름
        rank:
          type: string
          description: 사용자 계급
        title:
          type: string
          description: 사용자 직책
        status:
          type: string
          description: 사용자 상태
          enum: 
            - stop
            - sleep
            - gone
            - avail
            - deleted
        group:
          type: object
          description: 사용자 소속
        specialtyNumber:
          type: string
          description: 사용자 특기번호
        email:
          type: string
          description: 사용자 이메일
        tel:
          type: object
          properties:
            military:
              type: string
              description: 군 전화번호
            mobile:
              type: string
              pattern: '^\d{3}-\d{3,4}-\d{4}$'
              description: 휴대폰 전화번호
          description: 사용자 전화번호
        lastLogin:
          type: date
          description: 최종 접속 일시
        firstLogin:
          type: date
          description: 최초 접속 일시
        bookmarks:
          type: array
          description: 북마크 목록
        subscriptions:
          type: object
          properties:
            users:
              type: array
              description: 구독하는 사용자들
            groups:
              type: array
              description: 구독하는 그룹들
          description: 구독정보들
    Group:
      properties:
        name:
          type: string
          description: 부대 이름
        path:
          type: string
          description: 부대 경로
        admins:
          type: array
          description: 부대 관리자
        inspectors:
          type: array
          description: 부대 보안검수자




